//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCommerceDemo.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class articoliordineclienteweb
    {
        public long idarticolo { get; set; }
        public Nullable<decimal> ivavendita { get; set; }
        public string unitàmisura { get; set; }
        public Nullable<decimal> prezzofornitore { get; set; }
        public Nullable<decimal> sco1pf { get; set; }
        public Nullable<decimal> sco2pf { get; set; }
        public Nullable<decimal> sco3pf { get; set; }
        public Nullable<decimal> sco4pf { get; set; }
        public Nullable<decimal> deltapf { get; set; }
        public Nullable<decimal> ric1pf { get; set; }
        public Nullable<decimal> prezzodiacquistoscontatoricaricato { get; set; }
        public Nullable<decimal> ricaricosupacq { get; set; }
        public Nullable<decimal> prezzounitarioazienda { get; set; }
        public Nullable<decimal> sco1pa { get; set; }
        public Nullable<decimal> sco2pa { get; set; }
        public Nullable<decimal> sco3pa { get; set; }
        public Nullable<decimal> sco4pa { get; set; }
        public Nullable<decimal> ric1pa { get; set; }
        public Nullable<decimal> prezzounitariodivendita1 { get; set; }
        public Nullable<decimal> ric1pv { get; set; }
        public Nullable<decimal> prezzounitariodivendita2 { get; set; }
        public Nullable<decimal> pesoarticolo { get; set; }
        public string codicearticolo { get; set; }
        public string descrizionebrevearticolo { get; set; }
        public string codiceabarrearticolo { get; set; }
        public Nullable<decimal> larghezza { get; set; }
        public Nullable<decimal> lunghezza { get; set; }
        public Nullable<decimal> altezza { get; set; }
        public string unitàdimisuradim { get; set; }
        public Nullable<decimal> pesototale { get; set; }
        public Nullable<decimal> sviluppomisure { get; set; }
        public Nullable<decimal> dataoramodifica { get; set; }
        public string statoarticolo { get; set; }
        public string utente { get; set; }
        public Nullable<long> idutente { get; set; }
        public Nullable<decimal> quantità { get; set; }
        public string statocommessa { get; set; }
        public string colore { get; set; }
        public string note { get; set; }
        public Nullable<long> idaziendamaster { get; set; }
        public string aziendamaster { get; set; }
        public Nullable<bool> selezionato { get; set; }
        public Nullable<long> idmarca { get; set; }
        public Nullable<long> idlistino { get; set; }
        public string descrizionelistino { get; set; }
        public Nullable<decimal> prezzolistinoaut { get; set; }
        public Nullable<decimal> prezzolistinoman { get; set; }
        public string descrizionemarca { get; set; }
        public Nullable<decimal> ricarico2perpl { get; set; }
        public Nullable<long> idordine { get; set; }
        public string nummanualeordine { get; set; }
        public Nullable<System.DateTime> dataordine { get; set; }
        public Nullable<long> idcliente { get; set; }
        public string cliente { get; set; }
        public Nullable<decimal> prezzounitario { get; set; }
        public Nullable<decimal> percsconto1 { get; set; }
        public Nullable<decimal> percsconto2 { get; set; }
        public Nullable<decimal> percsconto3 { get; set; }
        public Nullable<decimal> percsconto4 { get; set; }
        public Nullable<decimal> percricarico1 { get; set; }
        public Nullable<decimal> percricarico2 { get; set; }
        public Nullable<decimal> periva { get; set; }
        public Nullable<decimal> totaleivaesclusa { get; set; }
        public Nullable<decimal> totaleivacompresa { get; set; }
        public string codiva { get; set; }
        public Nullable<decimal> coefk { get; set; }
    }
}
