//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCommerceDemo.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class datiordineclienteweb
    {
        public long idordine { get; set; }
        public Nullable<long> idcliente { get; set; }
        public string cliente { get; set; }
        public string notevarie { get; set; }
        public Nullable<decimal> dataoramodifica { get; set; }
        public string utente { get; set; }
        public Nullable<long> idutente { get; set; }
        public Nullable<bool> selezionato { get; set; }
        public Nullable<decimal> perciva { get; set; }
        public Nullable<decimal> totaleiva { get; set; }
        public Nullable<decimal> totaleivaesclusa { get; set; }
        public Nullable<decimal> totaleivacompresa { get; set; }
        public Nullable<decimal> totaleapagare { get; set; }
        public string destinazionemerce { get; set; }
        public string porto { get; set; }
        public string allacattenzione { get; set; }
        public string riferimentointerno { get; set; }
        public Nullable<System.DateTime> dataconsegnaprevista { get; set; }
        public string aziendamaster { get; set; }
        public Nullable<long> idaziendamaster { get; set; }
        public string riferimentoazienda { get; set; }
        public string statoordine { get; set; }
        public string nummanualeordine { get; set; }
        public Nullable<System.DateTime> dataordine { get; set; }
        public string metodoconsegna { get; set; }
        public Nullable<System.DateTime> dataconvalida { get; set; }
        public string utenteconvalida { get; set; }
        public string descrizioneordine { get; set; }
        public string numordineonel { get; set; }
        public Nullable<long> idordineonel { get; set; }
        public Nullable<System.DateTime> dataordineonel { get; set; }
        public string statoordineonel { get; set; }
        public string anomalie { get; set; }
        public Nullable<System.DateTime> dataconsegnaapprovata { get; set; }
        public string notestaff { get; set; }
    }
}
