//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCommerceDemo.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tuteweb
    {
        public long codice { get; set; }
        public string utente { get; set; }
        public string pswd { get; set; }
        public string abilitazione { get; set; }
        public string nome { get; set; }
        public string cognome { get; set; }
        public Nullable<bool> selezionato { get; set; }
        public string mail { get; set; }
        public Nullable<long> idaziendamaster { get; set; }
        public string aziendamaster { get; set; }
        public string gruppoprimario { get; set; }
        public string grupposecondario { get; set; }
        public Nullable<long> idcliente { get; set; }
        public string denominazionecliente { get; set; }
        public Nullable<long> usaordini { get; set; }
        public Nullable<long> usalistini { get; set; }
        public Nullable<long> usareclami { get; set; }
        public Nullable<long> usaverbali { get; set; }
        public Nullable<long> usafatclienti { get; set; }
        public Nullable<long> usafatfornitori { get; set; }
        public Nullable<long> idazindamasterinonelight { get; set; }
        public string mailutstaffassegnato { get; set; }
        public Nullable<long> dbsustessarete { get; set; }
        public string note { get; set; }
        public string linkprivacyazmaster { get; set; }
        public string server { get; set; }
        public Nullable<long> usacoefk { get; set; }
        public Nullable<long> usarappintervento { get; set; }
        public Nullable<long> usaaccantarticoli { get; set; }
        public Nullable<long> usavisualizcorsi { get; set; }
        public Nullable<long> cambiautenti { get; set; }
        public Nullable<long> veditutticli { get; set; }
        public Nullable<long> vedituttifor { get; set; }
        public Nullable<long> usaofferte { get; set; }
        public Nullable<long> Usaappuntamenti { get; set; }
        public Nullable<long> Usainterrogazioni { get; set; }
        public Nullable<long> Usaeventi { get; set; }
        public Nullable<long> Vediglialtricli { get; set; }
        public Nullable<long> Vedisoloassegnati { get; set; }
        public Nullable<long> Cambiastatiaccan { get; set; }
        public string tipouteperdashboard { get; set; }
        public string Shopoweb { get; set; }
    }
}
